server:
  port: 7003

eureka:
  instance:
    hostname: eureka7003.com # eureka服务端的实例名称
  client:
    # false端表示自己端就是注册中心，我的职责就是维护服务实例，并不需要检索服务
    fetch-registry: false
    # false表示不向注册中心注册自己
    register-with-eureka: false
    # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
    service-url:
      # 向7002
      defaultZone: http://eureka7001.com:7002/eureka/
  # 禁止保护模式
  #server:
  #  enable-self-preservation: false