server:
  port: 2003

spring:
  application:
    name: seata-account-service
  cloud:
    alibaba:
      seata:
        # 配置事务组名称，如果在seata安装目录下的conf目录下的file.conf文件中的server设置了自定义的事务组名称，
        # 则这里需要和file.conf文件中指定的自定义事务组名称一致
        tx-service-group: fsp_tx_group
    nacos:
        # nacos的地址
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    # 编写数据库相关连接信息
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.187.129:3306/seata_account
    username: root
    password: root

feign:
  hystrix:
    enabled: false

seata:
  enable-auto-data-source-proxy: true

  service:
    vgroup-mapping:
      fsp_tx_group: default

  config:
    nacos:
      # 配置registry.conf文件里指定的nacos的命名空间的命名空间ID。如果没有指定，就默认是public的命名空间，可以不用配置
      namespace: 548c2f72-862b-46d2-856d-403cdb1d6480
      group: SEATA_GROUP
      username: nacos
      password: nacos
      server-addr: 127.0.0.1:8848

  registry:
    nacos:
      application: seata-server
      cluster: default
      server-addr: 127.0.0.1:8848
      namespace: 548c2f72-862b-46d2-856d-403cdb1d6480
      username: nacos
      password: nacos
      group: SEATA_GROUP

mybatis:
  mapper-locations: classpath:mapper/*.xml
