server:
  port: 9008

spring:
  application:
    name: cloud-alibaba-stream-rocketmq-consumer-9008
  cloud:
    nacos:
      discovery:
        #配置Nacos地址
        server-addr: 39.108.105.55:8848
    stream:
      bindings:
        #input2: 订阅 topic 为 test-topic 的消息，异步消费 tags 为 tagStr 的消息，Consumer 端线程池个数为20
        input2:
          # 设置topic
          destination: test-topic
          content-type: application/json
          group: test-group2
          consumer:
            concurrency: 20

      rocketmq:
        binder:
          # 设置rocketmq nameserver地址
          name-server: 39.108.105.55:9876
        bindings:
          input2:
            consumer:
              orderly: false
              tags: tagStr




# 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'